GPUE:  GPU Gross-Pitaevskii Equation: LatticeGraph::Lattice Class Reference
LatticeGraph::Lattice Class Reference
#include <lattice.h>
Public Member Functions
Lattice ()
Makes stuff exist.
~Lattice ()
Makes stuff anti-exist.
void addEdge (std::shared_ptr< Edge > e)
Add edge e to the lattice (graph).
void addEdge (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Add edge between vortex (node) n1 and n2 to the lattice (graph).
void addEdge (std::shared_ptr< Edge > e, std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Add edge e between vortex (node) n1 and n2 to the lattice (graph).
void addVortex (std::shared_ptr< Node > n)
Add vortex (node) to the lattice (graph).
void adjMatMtca (unsigned int *mat)
Format adjacency matrix with Mathematica-friendly output.
void adjMatMtca (double *mat)
Format adjacency matrix with Mathematica-friendly output.
void createEdges (unsigned int radius)
Generate edges between vortices closer than int radius.
void createEdges (double radius)
Generate edges between vortices closer than double radius.
void createVortex (double posx, double posy, int winding)
Create a vortex at specified location with given winding.
void destroyVortex (unsigned int uid)
Destroy a vortex with UID uid.
void genAdjMat (unsigned int *mat)
Output adjacency matrix.
void genAdjMat (double *mat)
Output adjacency matrix.
std::shared_ptr< Edge > getEdgeIdx (unsigned int idx)
Returns edge specified at index idx.
unsigned int getEdgeIdxUid (unsigned int uid)
Returns edge index based on UID.
std::vector< std::shared_ptr< Edge > > & getEdges ()
Returns the edges for edges.
std::shared_ptr< Edge > getEdgeUid (unsigned int uid)
Returns edge based on UID.
double getVortexDistance (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Calculates distance between vortices.
double getVortexDistanceD (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Calculates distance between vortices.
std::shared_ptr< Node > getVortexIdx (unsigned int idx)
Returns vortex specified at index idx.
unsigned int getVortexIdxUid (unsigned int uid)
Returns vortex index based on UID.
std::shared_ptr< Node > getVortexUid (unsigned int uid)
Returns vortex based on UID.
std::vector< std::shared_ptr< Node > > & getVortices ()
Returns the vectors for vortices.
std::weak_ptr< Edge > isConnected (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Checks if vortex n1 and n2 are connected.
void removeEdge (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Remove edge between n1 and n2 from the lattice.
void removeEdge (std::shared_ptr< Edge > e)
Remove edge from the lattice.
void removeEdgeIdx (unsigned int idx)
Remove edge from the lattice based index idx.
void removeEdges (std::shared_ptr< Node > n1)
Remove all edges from vortex.
void removeEdgeUid (unsigned int uid)
Remove edge from the lattice based on UID uid.
void removeVortex (std::shared_ptr< Node > n)
Remove vortex n from the lattice.
void removeVortexIdx (unsigned int idx)
Remove vortex from the lattice based on index idx.
void removeVortexUid (unsigned int uid)
Remove vortex from the lattice based on UID uid.
void setEdge (unsigned int idx, std::shared_ptr< Edge > e)
Set edge at a specific position.
void setVortex (unsigned int idx, std::shared_ptr< Node > n)
Set vortex (node) at a specific position.
void swapIdx (unsigned int idx1, unsigned int idx2)
Swap the elements at indices idx1 and idx2.
void swapIdxUid (unsigned int uid1, unsigned int uid2)
Swap the elements at indices based on UID uid1 and uid2.
Private Attributes
std::vector< std::shared_ptr< Edge > > edges
std::vector< std::shared_ptr< Node > > vortices
Detailed Description
Definition at line 31 of file lattice.h.
Constructor & Destructor Documentation
Lattice()
LatticeGraph::Lattice::Lattice ()
Makes stuff exist.
~Lattice()
LatticeGraph::Lattice::~Lattice ()
Makes stuff anti-exist.
Member Function Documentation
addEdge() [1/3]
void LatticeGraph::Lattice::addEdge (std::shared_ptr< Edge > e)
Add edge e to the lattice (graph).
Assumes edge has nodes already.
Parameters
e Edge to add
Referenced by main().
addEdge() [2/3]
void LatticeGraph::Lattice::addEdge (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Add edge between vortex (node) n1 and n2 to the lattice (graph).
Parameters
n1 Vortex to add edge to as connection 1
n2 Vortex to add edge to as connection 2
addEdge() [3/3]
void LatticeGraph::Lattice::addEdge (std::shared_ptr< Edge > e, std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Add edge e between vortex (node) n1 and n2 to the lattice (graph).
Parameters
e Edge to add
n1 Vortex to add edge to as connection 1
n2 Vortex to add edge to as connection 2
addVortex()
void LatticeGraph::Lattice::addVortex (std::shared_ptr< Node > n)
Add vortex (node) to the lattice (graph).
Parameters
n Vortex to add
adjMatMtca() [1/2]
void LatticeGraph::Lattice::adjMatMtca (unsigned int * mat)
Format adjacency matrix with Mathematica-friendly output.
Parameters
*mat Adjacency matrix from genAdjMat(*uint)
Referenced by main().
adjMatMtca() [2/2]
void LatticeGraph::Lattice::adjMatMtca (double * mat)
Format adjacency matrix with Mathematica-friendly output.
Parameters
*mat Adjacency matrix from genAdjMat(*double)
createEdges() [1/2]
void LatticeGraph::Lattice::createEdges (unsigned int radius)
Generate edges between vortices closer than int radius.
Parameters
radius Radius cutoff for creating edge connections
createEdges() [2/2]
void LatticeGraph::Lattice::createEdges (double radius)
Generate edges between vortices closer than double radius.
Parameters
radius Radius cutoff for creating edge connections
createVortex()
void LatticeGraph::Lattice::createVortex (double posx, double posy, int winding)
Create a vortex at specified location with given winding.
Parameters
posx Position x to create vortex
posy Position y to create vortex
Winding of vortex to create
destroyVortex()
void LatticeGraph::Lattice::destroyVortex (unsigned int uid)
Destroy a vortex with UID uid.
Parameters
uid Vortex to destroy with UID uid
genAdjMat() [1/2]
void LatticeGraph::Lattice::genAdjMat (unsigned int * mat)
Output adjacency matrix.
Parameters
*mat Modifyable UInt array for adjacency matrix
Referenced by main().
genAdjMat() [2/2]
void LatticeGraph::Lattice::genAdjMat (double * mat)
Output adjacency matrix.
Parameters
*mat Modifyable double array for adjacency matrix
getEdgeIdx()
std::shared_ptr<Edge> LatticeGraph::Lattice::getEdgeIdx (unsigned int idx)
Returns edge specified at index idx.
Parameters
idx Index of vortex position
Returns
Shared pointer to edge at index idx
getEdgeIdxUid()
unsigned int LatticeGraph::Lattice::getEdgeIdxUid (unsigned int uid)
Returns edge index based on UID.
Parameters
uid UID of edge
Returns
Index of edge with UID uid
getEdges()
std::vector<std::shared_ptr <Edge> >& LatticeGraph::Lattice::getEdges ()
Returns the edges for edges.
Returns
Vector of shared_ptr for edges (Nodes)
getEdgeUid()
std::shared_ptr<Edge> LatticeGraph::Lattice::getEdgeUid (unsigned int uid)
Returns edge based on UID.
Parameters
uid UID of edge
Returns
edge with UID uid
Bug:
Fails for vortex UIDs that do not exist. Assumes they do.
getVortexDistance()
double LatticeGraph::Lattice::getVortexDistance (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Calculates distance between vortices.
Parameters
n1 Vortex (node) 1
n2 Vortex (node) 2
Returns
double of intervortex distance
getVortexDistanceD()
double LatticeGraph::Lattice::getVortexDistanceD (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Calculates distance between vortices.
Parameters
n1 Vortex (node) 1
n2 Vortex (node) 2
Returns
double of intervortex distance
getVortexIdx()
std::shared_ptr<Node> LatticeGraph::Lattice::getVortexIdx (unsigned int idx)
Returns vortex specified at index idx.
Parameters
idx Index of vortex position
Returns
Shared pointer to vortex (Node) at index idx
Referenced by main().
getVortexIdxUid()
unsigned int LatticeGraph::Lattice::getVortexIdxUid (unsigned int uid)
Returns vortex index based on UID.
Parameters
uid UID of vortex
Returns
Index of vortex with UID uid
getVortexUid()
std::shared_ptr<Node> LatticeGraph::Lattice::getVortexUid (unsigned int uid)
Returns vortex based on UID.
Parameters
uid UID of vortex
Returns
Vortex with UID uid
Bug:
Fails for vortex UIDs that do not exist. Assumes they do.
getVortices()
std::vector<std::shared_ptr <Node> >& LatticeGraph::Lattice::getVortices ()
Returns the vectors for vortices.
Returns
Vector of shared_ptr for vortices (Nodes)
Referenced by main().
isConnected()
std::weak_ptr<Edge> LatticeGraph::Lattice::isConnected (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Checks if vortex n1 and n2 are connected.
Parameters
n1 Vortex (node) 1
n2 Vortex (node) 2
Returns
Weak pointer to the connecting edge
removeEdge() [1/2]
void LatticeGraph::Lattice::removeEdge (std::shared_ptr< Node > n1, std::shared_ptr< Node > n2)
Remove edge between n1 and n2 from the lattice.
Parameters
n1 Vortex 1
n2 Vortex 2
removeEdge() [2/2]
void LatticeGraph::Lattice::removeEdge (std::shared_ptr< Edge > e)
Remove edge from the lattice.
Parameters
e Edge to remove
removeEdgeIdx()
void LatticeGraph::Lattice::removeEdgeIdx (unsigned int idx)
Remove edge from the lattice based index idx.
Parameters
idx Edge at index idx to remove
removeEdges()
void LatticeGraph::Lattice::removeEdges (std::shared_ptr< Node > n1)
Remove all edges from vortex.
Parameters
n1 Vortex (node) to lose all edges
removeEdgeUid()
void LatticeGraph::Lattice::removeEdgeUid (unsigned int uid)
Remove edge from the lattice based on UID uid.
Parameters
uid Edge with UID uid to remove
Referenced by main().
removeVortex()
void LatticeGraph::Lattice::removeVortex (std::shared_ptr< Node > n)
Remove vortex n from the lattice.
Parameters
n Vortex (node) to remove
removeVortexIdx()
void LatticeGraph::Lattice::removeVortexIdx (unsigned int idx)
Remove vortex from the lattice based on index idx.
Parameters
idx Vortex at index idx to remove
removeVortexUid()
void LatticeGraph::Lattice::removeVortexUid (unsigned int uid)
Remove vortex from the lattice based on UID uid.
Parameters
uid Vortex with UID uid to remove
setEdge()
void LatticeGraph::Lattice::setEdge (unsigned int idx, std::shared_ptr< Edge > e)
Set edge at a specific position.
Parameters
idx Index to set vortex
n Vortex to set
setVortex()
void LatticeGraph::Lattice::setVortex (unsigned int idx, std::shared_ptr< Node > n)
Set vortex (node) at a specific position.
Parameters
idx Index to set vortex
n Vortex to set
swapIdx()
void LatticeGraph::Lattice::swapIdx (unsigned int idx1, unsigned int idx2)
Swap the elements at indices idx1 and idx2.
Parameters
idx1 Index of element 1
idx2 Index of element 2
swapIdxUid()
void LatticeGraph::Lattice::swapIdxUid (unsigned int uid1, unsigned int uid2)
Swap the elements at indices based on UID uid1 and uid2.
Parameters
uid1 UID of element 1 to swap
uid2 UID of element 2 to swap
Referenced by main().
Member Data Documentation
edges
std::vector<std::shared_ptr <Edge> > LatticeGraph::Lattice::edges private
Definition at line 35 of file lattice.h.
vortices
std::vector<std::shared_ptr <Node> > LatticeGraph::Lattice::vortices private
Definition at line 34 of file lattice.h.
The documentation for this class was generated from the following file:
/Users/mlxd/Desktop/GPUE/include/lattice.h