GPUE:  GPU Gross-Pitaevskii Equation: /home/james/projects/GPUE/CMakeFiles/3.10.2/CompilerIdCUDA/tmp/CMakeCUDACompilerId.cudafe1.cpp File Reference
CMakeCUDACompilerId.cudafe1.cpp File Reference
#include "crt/host_runtime.h"
Classes
struct max_align_t
Macros
#define __nv_is_extended_device_lambda_closure_type(X) false
#define __nv_is_extended_host_device_lambda_closure_type(X) false
Typedefs
typedef long ptrdiff_t
typedef unsigned long size_t
Functions
typedef __decltype ((nullptr)) nullptr_t
static void __nv_init_managed_rt (void)
static char __nv_init_managed_rt_with_module (void **)
static void __nv_save_fatbinhandle_for_managed_rt (void **in)
Variables
static void ** __nv_fatbinhandle_for_managed_rt
static char __nv_inited_managed_rt = 0
Macro Definition Documentation
__nv_is_extended_device_lambda_closure_type
#define __nv_is_extended_device_lambda_closure_type (X) false
Definition at line 17 of file CMakeCUDACompilerId.cudafe1.cpp.
__nv_is_extended_host_device_lambda_closure_type
#define __nv_is_extended_host_device_lambda_closure_type (X) false
Definition at line 18 of file CMakeCUDACompilerId.cudafe1.cpp.
Typedef Documentation
ptrdiff_t
typedef long ptrdiff_t
Definition at line 756 of file CMakeCUDACompilerId.cudafe1.cpp.
size_t
typedef unsigned long size_t
Definition at line 758 of file CMakeCUDACompilerId.cudafe1.cpp.
Function Documentation
__decltype()
typedef __decltype ((nullptr))
__nv_init_managed_rt()
static void __nv_init_managed_rt (void) inline static
Definition at line 10 of file CMakeCUDACompilerId.cudafe1.cpp.
Referenced by __nv_save_fatbinhandle_for_managed_rt().
 {__nv_fatbinhandle_for_managed_rt = in;} static char __nv_init_managed_rt_with_module(void **); static inline void __nv_init_managed_rt(void) { __nv_inited_managed_rt = (__nv_inited_managed_rt ? __nv_inited_managed_rt                 : __nv_init_managed_rt_with_module(__nv_fatbinhandle_for_managed_rt));}
__nv_init_managed_rt_with_module()
static char __nv_init_managed_rt_with_module (void **) static
Referenced by __nv_save_fatbinhandle_for_managed_rt().
__nv_save_fatbinhandle_for_managed_rt()
static void __nv_save_fatbinhandle_for_managed_rt (void ** in) static
Definition at line 10 of file CMakeCUDACompilerId.cudafe1.cpp.
References __nv_fatbinhandle_for_managed_rt, __nv_init_managed_rt(), __nv_init_managed_rt_with_module(), and __nv_inited_managed_rt.
 {__nv_fatbinhandle_for_managed_rt = in;} static char __nv_init_managed_rt_with_module(void **); static inline void __nv_init_managed_rt(void) { __nv_inited_managed_rt = (__nv_inited_managed_rt ? __nv_inited_managed_rt                 : __nv_init_managed_rt_with_module(__nv_fatbinhandle_for_managed_rt));}
Variable Documentation
__nv_fatbinhandle_for_managed_rt
void** __nv_fatbinhandle_for_managed_rt static
Definition at line 10 of file CMakeCUDACompilerId.cudafe1.cpp.
Referenced by __nv_save_fatbinhandle_for_managed_rt().
__nv_inited_managed_rt
char __nv_inited_managed_rt = 0 static
Definition at line 10 of file CMakeCUDACompilerId.cudafe1.cpp.
Referenced by __nv_save_fatbinhandle_for_managed_rt().