var namespaces =
[
    [ "en", "namespaceen.html", null ],
    [ "extract_gauge", "namespaceextract__gauge.html", null ],
    [ "FileIO", "namespaceFileIO.html", null ],
    [ "find_scissors_angle", "namespacefind__scissors__angle.html", null ],
    [ "gen_data", "namespacegen__data.html", null ],
    [ "hist3d", "namespacehist3d.html", null ],
    [ "hist_it", "namespacehist__it.html", null ],
    [ "LatticeGraph", "namespaceLatticeGraph.html", null ],
    [ "Minions", "namespaceMinions.html", null ],
    [ "observables", "namespaceobservables.html", null ],
    [ "paraview_plot", "namespaceparaview__plot.html", null ],
    [ "plot", "namespaceplot.html", null ],
    [ "scissors", "namespacescissors.html", null ],
    [ "scissors_0", "namespacescissors__0.html", null ],
    [ "scissors_check", "namespacescissors__check.html", null ],
    [ "script1", "namespacescript1.html", null ],
    [ "stats", "namespacestats.html", null ],
    [ "Tracker", "namespaceTracker.html", null ],
    [ "vis", "namespacevis.html", null ],
    [ "vis_scripts", "namespacevis__scripts.html", null ],
    [ "visualize_3d", "namespacevisualize__3d.html", null ],
    [ "vort", "namespacevort.html", null ],
    [ "Vtx", "namespaceVtx.html", null ],
    [ "WFC", "namespaceWFC.html", null ]
];