GPUE:  GPU Gross-Pitaevskii Equation: vort Namespace Reference
vort Namespace Reference
Classes
class Vortex
class VtxList
Functions
def __init__ (self, uid, x, y, isOn, sign=1)
def __init__ (self)
def add (self, Vtx, index=None)
def as_np (self)
def dist (self, vtx)
def do_the_thing (start, fin, incr)
def element (self, pos)
def idx_min_dist (self, vortex, isSelf=False)
def max_uid (self)
def remove (self, pos)
def swap_uid (self, uid_i, uid_f)
def update_next (self, next)
def update_on (self, isOn)
def update_uid (self, uid)
def vort_decrease (self, positions, vorts_p)
def vort_increase (self, positions, vorts_p)
def vtx_uid (self, uid)
def write_out (self, time, data)
Variables
c = ConfigParser.ConfigParser()
int counter = 0
def current = self.element(pos-1).next
list data = []
string data_dir = "../" + sys.argv[1] + "/"
dcp = set(uid_c).difference(set(uid_p))
delimiter
dpc = set(uid_p).difference(set(uid_c))
tuple dt = (c.getfloat('Params','dt'))
list dtype = [('x',float),('y',float),('sign',int),('uid',int),('isOn',int)]
tuple dx = (c.getfloat('Params','dx'))
evMaxVal = int(c.getfloat('Params','esteps'))
fmt
gndMaxVal = int(c.getfloat('Params','gsteps'))
head
int i = 0
incr = int(c.getfloat('Params','printSteps'))
index
def index_r = vorts_c.idx_min_dist(vorts_p.element(i3))
isOn
length
def max_uid = vorts_p.max_uid()
next
int pos = 0
int pos_l = 0
r = m.sqrt((self.x - vtx.x)**2 + (self.y - vtx.y)**2)
int ret_idx = counter
sign
tail
uid
list uid_c = [[a for a in b][3] for b in vorts_c.as_np()]
list uid_p = [[a for a in b][3] for b in vorts_p.as_np()]
def v0c = vorts_c.element(index_r[0]).sign
def v0p = vorts_p.element(i3).sign
def v1c = vorts_c.element(index_r[0]).uid
v_arr_c = genfromtxt(data_dir+'vort_arr_' + str(i), delimiter=',')
v_arr_c_coords = np.array([a for a in v_arr_c[:,[1,3]]])
v_arr_c_sign = np.array([a for a in v_arr_c[:,4]])
v_arr_p = genfromtxt(data_dir+'vort_arr_' + str(incr),delimiter=',')
v_arr_p_coords = np.array([a for a in v_arr_p[:,[1,3]]])
v_arr_p_sign = np.array([a for a in v_arr_p[:,4]])
int val = 0
vorts_c = VtxList()
vorts_c_update = sorted(vorts_c.as_np(),key=lambda vtx: vtx[3])
vorts_p = VtxList()
vtx = self.head
vtx_c = Vortex(-1-i2,v_arr_c_coords[i2][0],v_arr_c_coords[i2][1],True,sign=v_arr_c_sign[i2])
vtx_p = Vortex(i1,v_arr_p_coords[i1][0],v_arr_p_coords[i1][1],True,sign=v_arr_p_sign[i1])
def vtx_pos = self.vtx_uid(uid_i)
list vtx_pos_c = []
list vtx_pos_p = []
x
xDim = int(c.getfloat('Params','xDim'))
tuple xMax = (c.getfloat('Params','xMax'))
y
yDim = int(c.getfloat('Params','yDim'))
tuple yMax = (c.getfloat('Params','yMax'))
Class Documentation
vort::Vortex
class vort::Vortex
Definition at line 34 of file vort.py.
vort::VtxList
class vort::VtxList
Definition at line 68 of file vort.py.
Function Documentation
__init__() [1/2]
def vort.__init__ (self, uid, x, y, isOn, sign = 1)
Definition at line 37 of file vort.py.
Referenced by __init__().
     def __init__(self,uid,x,y,isOn,sign=1):
__init__() [2/2]
def vort.__init__ (self)
Definition at line 71 of file vort.py.
References __init__().
     def __init__(self):
add()
def vort.add (self, Vtx, index = None)
Definition at line 119 of file vort.py.
     def add(self,Vtx,index=None): #Add a vtx at index, otherwise end
as_np()
def vort.as_np (self)
Definition at line 135 of file vort.py.
     def as_np(self): #Return numpy array with format x,y,sign,uid,isOn
dist()
def vort.dist (self, vtx)
Definition at line 62 of file vort.py.
Referenced by main().
     def dist(self,vtx): #Distance between self and vtx
do_the_thing()
def vort.do_the_thing (start, fin, incr)
Definition at line 215 of file vort.py.
 def do_the_thing(start,fin,incr): #Performs the tracking
element()
def vort.element (self, pos)
Definition at line 78 of file vort.py.
     def element(self,pos): #Get vtx at position pos
idx_min_dist()
def vort.idx_min_dist (self, vortex, isSelf = False)
Definition at line 153 of file vort.py.
     def idx_min_dist(self,vortex, isSelf=False): #Closest vtx to self
max_uid()
def vort.max_uid (self)
Definition at line 102 of file vort.py.
References max_uid.
     def max_uid(self): #Return position and value of largest uid
remove()
def vort.remove (self, pos)
Definition at line 169 of file vort.py.
     def remove(self,pos): #Remove vortices outside artificial boundary
swap_uid()
def vort.swap_uid (self, uid_i, uid_f)
Definition at line 188 of file vort.py.
     def swap_uid(self,uid_i,uid_f): #Swap uid between vtx
update_next()
def vort.update_next (self, next)
Definition at line 57 of file vort.py.
     def update_next(self,next): #Get next vortex
update_on()
def vort.update_on (self, isOn)
Definition at line 52 of file vort.py.
     def update_on(self,isOn): #Vortex is trackable
update_uid()
def vort.update_uid (self, uid)
Definition at line 47 of file vort.py.
     def update_uid(self,uid):
vort_decrease()
def vort.vort_decrease (self, positions, vorts_p)
Definition at line 195 of file vort.py.
     def vort_decrease(self,positions,vorts_p): #Turn off vortex timeline
vort_increase()
def vort.vort_increase (self, positions, vorts_p)
Definition at line 205 of file vort.py.
     def vort_increase(self,positions,vorts_p): #Add new vtx to tracking
vtx_uid()
def vort.vtx_uid (self, uid)
Definition at line 92 of file vort.py.
     def vtx_uid(self,uid): #Get vtx with identifier uid
write_out()
def vort.write_out (self, time, data)
Definition at line 148 of file vort.py.
     def write_out(self,time,data): #Write out CSV file as  x,y,sign,uid,isOn
Variable Documentation
c
vort.c = ConfigParser.ConfigParser()
Definition at line 15 of file vort.py.
counter
int vort.counter = 0
Definition at line 155 of file vort.py.
current
vort.current = self.element(pos-1).next
Definition at line 172 of file vort.py.
data
vort.data = []
Definition at line 138 of file vort.py.
data_dir
string vort.data_dir = "../" + sys.argv[1] + "/"
Definition at line 12 of file vort.py.
dcp
vort.dcp = set(uid_c).difference(set(uid_p))
Definition at line 257 of file vort.py.
delimiter
vort.delimiter
Definition at line 150 of file vort.py.
dpc
vort.dpc = set(uid_p).difference(set(uid_c))
Definition at line 256 of file vort.py.
dt
tuple vort.dt = (c.getfloat('Params','dt'))
Definition at line 24 of file vort.py.
dtype
list vort.dtype = [('x',float),('y',float),('sign',int),('uid',int),('isOn',int)]
Definition at line 137 of file vort.py.
dx
tuple vort.dx = (c.getfloat('Params','dx'))
Definition at line 23 of file vort.py.
evMaxVal
vort.evMaxVal = int(c.getfloat('Params','esteps'))
Definition at line 21 of file vort.py.
fmt
vort.fmt
Definition at line 150 of file vort.py.
gndMaxVal
vort.gndMaxVal = int(c.getfloat('Params','gsteps'))
Definition at line 20 of file vort.py.
head
vort.head
Definition at line 73 of file vort.py.
i
int vort.i = 0
Definition at line 139 of file vort.py.
incr
vort.incr = int(c.getfloat('Params','printSteps'))
Definition at line 22 of file vort.py.
index
vort.index
Definition at line 192 of file vort.py.
index_r
def vort.index_r = vorts_c.idx_min_dist(vorts_p.element(i3))
Definition at line 242 of file vort.py.
isOn
vort.isOn
Definition at line 43 of file vort.py.
length
vort.length
Definition at line 75 of file vort.py.
Referenced by sepAvg().
max_uid
def vort.max_uid = vorts_p.max_uid()
Definition at line 208 of file vort.py.
Referenced by max_uid().
next
vort.next
Definition at line 44 of file vort.py.
pos
int vort.pos = 0
Definition at line 95 of file vort.py.
pos_l
int vort.pos_l = 0
Definition at line 80 of file vort.py.
r
def vort.r = m.sqrt((self.x - vtx.x)**2 + (self.y - vtx.y)**2)
Definition at line 64 of file vort.py.
ret_idx
int vort.ret_idx = counter
Definition at line 156 of file vort.py.
sign
vort.sign
Definition at line 42 of file vort.py.
tail
vort.tail
Definition at line 74 of file vort.py.
uid
vort.uid
Definition at line 39 of file vort.py.
uid_c
list vort.uid_c = [[a for a in b][3] for b in vorts_c.as_np()]
Definition at line 253 of file vort.py.
uid_p
list vort.uid_p = [[a for a in b][3] for b in vorts_p.as_np()]
Definition at line 254 of file vort.py.
v0c
def vort.v0c = vorts_c.element(index_r[0]).sign
Definition at line 244 of file vort.py.
v0p
def vort.v0p = vorts_p.element(i3).sign
Definition at line 245 of file vort.py.
v1c
def vort.v1c = vorts_c.element(index_r[0]).uid
Definition at line 246 of file vort.py.
v_arr_c
vort.v_arr_c = genfromtxt(data_dir+'vort_arr_' + str(i), delimiter=',')
Definition at line 221 of file vort.py.
v_arr_c_coords
vort.v_arr_c_coords = np.array([a for a in v_arr_c[:,[1,3]]])
Definition at line 224 of file vort.py.
v_arr_c_sign
vort.v_arr_c_sign = np.array([a for a in v_arr_c[:,4]])
Definition at line 226 of file vort.py.
v_arr_p
vort.v_arr_p = genfromtxt(data_dir+'vort_arr_' + str(incr),delimiter=',')
Definition at line 217 of file vort.py.
v_arr_p_coords
vort.v_arr_p_coords = np.array([a for a in v_arr_p[:,[1,3]]])
Definition at line 223 of file vort.py.
v_arr_p_sign
vort.v_arr_p_sign = np.array([a for a in v_arr_p[:,4]])
Definition at line 225 of file vort.py.
val
vort.val = 0
Definition at line 104 of file vort.py.
vorts_c
vort.vorts_c = VtxList()
Definition at line 220 of file vort.py.
vorts_c_update
vort.vorts_c_update = sorted(vorts_c.as_np(),key=lambda vtx: vtx[3])
Definition at line 270 of file vort.py.
vorts_p
vort.vorts_p = VtxList()
Definition at line 219 of file vort.py.
vtx
vort.vtx = self.head
Definition at line 82 of file vort.py.
vtx_c
vort.vtx_c = Vortex(-1-i2,v_arr_c_coords[i2][0],v_arr_c_coords[i2][1],True,sign=v_arr_c_sign[i2])
Definition at line 238 of file vort.py.
vtx_p
vort.vtx_p = Vortex(i1,v_arr_p_coords[i1][0],v_arr_p_coords[i1][1],True,sign=v_arr_p_sign[i1])
Definition at line 234 of file vort.py.
vtx_pos
def vort.vtx_pos = self.vtx_uid(uid_i)
Definition at line 190 of file vort.py.
vtx_pos_c
vort.vtx_pos_c = []
Definition at line 259 of file vort.py.
vtx_pos_p
vort.vtx_pos_p = []
Definition at line 258 of file vort.py.
x
vort.x
Definition at line 40 of file vort.py.
xDim
vort.xDim = int(c.getfloat('Params','xDim'))
Definition at line 18 of file vort.py.
xMax
tuple vort.xMax = (c.getfloat('Params','xMax'))
Definition at line 25 of file vort.py.
y
vort.y
Definition at line 41 of file vort.py.
yDim
vort.yDim = int(c.getfloat('Params','yDim'))
Definition at line 19 of file vort.py.
yMax
tuple vort.yMax = (c.getfloat('Params','yMax'))
Definition at line 26 of file vort.py.