GPUE: vis Namespace Reference
vis Namespace Reference
Functions
def delaunay (dataName, dataType, value)
def voronoi (dataName, dataType, value)
def laplacian (density, name, imgdpi)
def struct_fact (density, name, imgdpi)
def opPot (dataName, imgdpi)
def hist_gen (name, value, num_bins)
def image_gen (dataName, initValue, finalValue, increment, imgdpi)
def image_gen_single (dataName, value, imgdpi, opmode)
def vort_traj (name, imgdpi)
def scaleAxis (data, dataName, label, value, imgdpi)
def overlap (dataName, initValue, finalValue, increment)
Variables
CPUs = os.environ['SLURM_JOB_CPUS_PER_NODE']
prec
c = ConfigParser.ConfigParser()
xDim = int(c.getfloat('Params','xDim'))
yDim = int(c.getfloat('Params','yDim'))
gndMaxVal = int(c.getfloat('Params','gsteps'))
evMaxVal = int(c.getfloat('Params','esteps'))
incr = int(c.getfloat('Params','print_out'))
tuple sep = (c.getfloat('Params','dx'))
tuple dx = (c.getfloat('Params','dx'))
tuple dt = (c.getfloat('Params','dt'))
tuple xMax = (c.getfloat('Params','xMax'))
tuple yMax = (c.getfloat('Params','yMax'))
int num_vort = 0
data = numpy.ndarray(shape=(xDim,yDim))
list gndImgList = []
list evImgList = []
list gnd_proc = []
list ev_proc = []
list i = gndImgList.pop()
list proc = gnd_proc + ev_proc
list p = proc.pop()
Function Documentation
delaunay()
def vis.delaunay (dataName, dataType, value)
Definition at line 54 of file vis.py.
 def delaunay(dataName,dataType,value):
     v_arr=genfromtxt(dataName + str(value) + dataType,delimiter=',' )
     data = np.array([[row[0],row[1]] for row in v_arr])
     dln = sp.spatial.Delaunay(data)
     plt.triplot(data[:,0],data[:,1],dln.simplices.copy(),linewidth=0.5,color='b',marker='.')
     plt.xlim(300,700);plt.ylim(300,700);
     plt.savefig('delaun_' + str(value) + '.png',dpi=200)
     print 'Saved Delaunay @ t=' + str(value)
hist_gen()
def vis.hist_gen (name, value, num_bins)
Definition at line 109 of file vis.py.
 def hist_gen(name,value,num_bins):
     v_arr=genfromtxt('vort_arr_' + str(value),delimiter=',' )
     H=[]
     count=0
     for i1 in range(0,v_arr.size/2):
         for i2 in range(i1,v_arr.size/2):
             H.append(m.sqrt( abs(v_arr[i1][0]*sep - v_arr[i2][0]*sep)**2  +  abs(v_arr[i1][1]*sep - v_arr[i2][1]*sep)**2 ))
             count = count + 1
     plt.title('Vortex lattice @ t=' + str(value*dt))
     plt.ticklabel_format(style='scientific')
     plt.ticklabel_format(style='scientific',axis='x', scilimits=(0,0))
     h = plt.hist(H, bins=num_bins)
     plt.savefig(name + "_" + str(value) + ".pdf")
     plt.close()
image_gen()
def vis.image_gen (dataName, initValue, finalValue, increment, imgdpi)
Definition at line 125 of file vis.py.
 def image_gen(dataName, initValue, finalValue, increment,imgdpi):
     for i in range(initValue,finalValue,increment):
         if not os.path.exists(dataName+"r_"+str(i)+"_abspsi2.png"):
             real=open(dataName + '_' + str(i)).read().splitlines()
             img=open(dataName + 'i_' + str(i)).read().splitlines()
             a_r = numpy.asanyarray(real,dtype='f8') #64-bit double
             a_i = numpy.asanyarray(img,dtype='f8') #64-bit double
             a = a_r[:] + 1j*a_i[:]
             b = np.reshape(a,(xDim,yDim))
             f = plt.imshow(abs(b)**2)
             plt.jet()
             plt.gca().invert_yaxis()
             plt.savefig(dataName+"r_"+str(i)+"_abspsi2.png",dpi=imgdpi)
             plt.close()
             g = plt.imshow(np.angle(b))
             plt.gca().invert_yaxis()
             plt.savefig(dataName+"r_"+str(i)+"_phi.png",dpi=imgdpi)
             plt.close()
             f = plt.imshow(abs(np.fft.fftshift(np.fft.fft2(b)))**2)
             plt.gca().invert_yaxis()
             plt.jet()
             plt.savefig(dataName+"p_"+str(i)+"_abspsi2.png",dpi=imgdpi)
             plt.close()
             g = plt.imshow(np.angle(np.fft.fftshift(np.fft.fft2(b))))
             plt.gca().invert_yaxis()
             plt.savefig(dataName+"p_"+str(i)+"_phi.png",dpi=imgdpi)
             plt.close()
             print "Saved figure: " + str(i) + ".png"
             plt.close()
         else:
             print "File(s) " + str(i) +".png already exist."
image_gen_single()
def vis.image_gen_single (dataName, value, imgdpi, opmode)
Definition at line 157 of file vis.py.
References laplacian(), and struct_fact().
 def image_gen_single(dataName, value, imgdpi,opmode):
     real=open(dataName + '_' + str(0)).read().splitlines()
     img=open(dataName + 'i_' + str(0)).read().splitlines()
     a1_r = numpy.asanyarray(real,dtype='f8') #128-bit complex
     a1_i = numpy.asanyarray(img,dtype='f8') #128-bit complex
     a1 = a1_r[:] + 1j*a1_i[:]
     b1 = np.reshape(a1,(xDim,yDim))
     if not os.path.exists(dataName+"r_"+str(value)+"_abspsi2.png"):
         real=open(dataName + '_' + str(value)).read().splitlines()
         img=open(dataName + 'i_' + str(value)).read().splitlines()
         a_r = numpy.asanyarray(real,dtype='f8') #128-bit complex
         a_i = numpy.asanyarray(img,dtype='f8') #128-bit complex
         a = a_r[:] + 1j*a_i[:]
         b = np.reshape(a,(xDim,yDim))
         m_val=np.max(np.abs(b)**2)
         #scaleAxis(b,dataName,"_abspsi2",value,imgdpi)
         if opmode & 0b100000 > 0:
 #           fig, ax = plt.subplots()
 #           #plt.rc('text',usetex=True)
 #           #plt.rc('font',family='serif')
 #           f = plt.imshow((abs(b)**2 - abs(b1)**2),cmap='gnuplot2',vmin=-6,vmax=6)
 #           plt.title(r'$\left(\rho( r,t ) - \rho( r,t_0 )\right),t=$' + str(value*dt))
 #           cbar = fig.colorbar(f)
 #           plt.gca().set_xlabel('x '+ str((dx)))
 #           plt.gca().set_ylabel('x '+ str(dx))
 #           plt.gca().invert_yaxis()
 #           plt.savefig(dataName+"r_"+str(value)+"_diffabspsi2.png",dpi=imgdpi)
 #           plt.close()
 #           #plt.rc('text',usetex=True)
 #           #plt.rc('font',family='serif')
             fig, ax = plt.subplots()
             f = plt.imshow((abs(b)**2),cmap='gnuplot2',vmin=0,vmax=1e7)
             plt.title('rho(r) @ t=' + str(value*dt))
         #   plt.title(r'$\\rho \left( r,t \right),\,t=$' + str(value*dt))
             #plugins.connect(fig, plugins.MousePosition(fontsize=14))
             cbar = fig.colorbar(f)
             plt.gca().set_xlabel('x '+ str((dx)))
             plt.gca().set_ylabel('x '+ str(dx))
             plt.gca().invert_yaxis()
             plt.savefig(dataName+"r_"+str(value)+"_abspsi2.png",dpi=imgdpi)
             plt.axis('off')
             plt.savefig(dataName+"r_"+str(value)+"_abspsi2_axis0.pdf",bbox_inches='tight',dpi=imgdpi)
             plt.close()
         if opmode & 0b010000 > 0:
             fig, ax = plt.subplots()
             g = plt.imshow(np.angle(b))
             cbar = fig.colorbar(g)
             plt.gca().invert_yaxis()
             plt.title('theta(r) @ t=' + str(value*dt))
             plt.savefig(dataName+"r_"+str(value)+"_phi.png",dpi=imgdpi)
             plt.close()
         if opmode & 0b001000 > 0:
             fig, ax = plt.subplots()
             f = plt.imshow(abs(np.fft.fftshift(np.fft.fft2(b)))**2)
             cbar = fig.colorbar(f)
             plt.gca().invert_yaxis()
             plt.jet()
             plt.title('rho(p) @ t=' + str(value*dt))
             plt.savefig(dataName+"p_"+str(value)+"_abspsi2.png",dpi=imgdpi)
             plt.close()
         if opmode & 0b000100 > 0:
             fig, ax = plt.subplots()
             g = plt.imshow(np.angle(np.fft.fftshift(np.fft.fft2(b))))
             cbar = fig.colorbar(g)
             plt.gca().invert_yaxis()
             plt.title('theta(p) @ t=' + str(value*dt))
             plt.savefig(dataName+"p_"+str(value)+"_phi.png",dpi=imgdpi)
             plt.close()
         if opmode & 0b000010 > 0:
             struct_fact(abs(b)**2,dataName+"_" + str(value),imgdpi)
         if opmode & 0b000001 > 0:
             laplacian(abs(b)**2,dataName+"_" + str(value),imgdpi)
         print "Saved figure: " + str(value) + ".png"
         plt.close()
     else:
         print "File(s) " + str(value) +".png already exist."
laplacian()
def vis.laplacian (density, name, imgdpi)
Definition at line 72 of file vis.py.
Referenced by image_gen_single().
 def laplacian(density,name,imgdpi):
     gx,gy = np.gradient(density)
     g2x,gxgy = np.gradient(gx)
     gygx,g2y = np.gradient(gy)
     fig, ax = plt.subplots()
     #f = plt.quiver(gx,gy)
     f = plt.imshow((g2x**2 + g2y**2),cmap=plt.get_cmap('spectral'))
     cbar = fig.colorbar(f)
     plt.savefig(name + "_laplacian.png",dpi=imgdpi)
     plt.close()
     f = plt.imshow((gxgy - gygx),cmap=plt.get_cmap('spectral'))
     cbar = fig.colorbar(f)
     plt.savefig(name + "_dxdy.png",dpi=imgdpi)
     plt.close()
opPot()
def vis.opPot (dataName, imgdpi)
Definition at line 97 of file vis.py.
Referenced by overlap().
 def opPot(dataName,imgdpi):
     data = open(dataName).read().splitlines()
     a = numpy.asanyarray(data,dtype='f8')
     b = np.reshape(a,(xDim,yDim))
     fig, ax = plt.subplots()
     f = plt.imshow((b))
     plt.gca().invert_yaxis()
     cbar = fig.colorbar(f)
     plt.jet()
     plt.savefig(dataName + ".png",dpi=imgdpi)
     plt.close()
overlap()
def vis.overlap (dataName, initValue, finalValue, increment)
Definition at line 285 of file vis.py.
References opPot().
 def overlap(dataName, initValue, finalValue, increment):
     real=open(dataName + '_' + str(0)).read().splitlines()
     img=open(dataName + 'i_' + str(0)).read().splitlines()
     a_r = numpy.asanyarray(real,dtype='f8') #128-bit complex
     a_i = numpy.asanyarray(img,dtype='f8') #128-bit complex
     wfc0 = a_r[:] + 1j*a_i[:]
     for i in range(initValue,finalValue,increment):
         real=open(dataName + '_' + str(value)).read().splitlines()
         img=open(dataName + 'i_' + str(value)).read().splitlines()
         a_r = numpy.asanyarray(real,dtype='f8') #128-bit complex
         a_i = numpy.asanyarray(img,dtype='f8') #128-bit complex
         a = a_r[:] + 1j*a_i[:]
         b = np.dot(wfc0,a)
         print i, np.sum(b)
scaleAxis()
def vis.scaleAxis (data, dataName, label, value, imgdpi)
Definition at line 274 of file vis.py.
 def scaleAxis(data,dataName,label,value,imgdpi):
     fig, ax = plt.subplots()
     ax.xaxis.set_major_locator(ScaledLocator(dx=dx))
     ax.xaxis.set_major_formatter(ScaledLocator(dx=dx))
     f = plt.imshow(abs(data)**2)
     cbar = fig.colorbar(f)
     plt.gca().invert_yaxis()
     plt.jet()
     plt.savefig(dataName+"r_"+str(value)+"_"+label +".png",dpi=imgdpi)
     plt.close()
struct_fact()
def vis.struct_fact (density, name, imgdpi)
Definition at line 87 of file vis.py.
Referenced by image_gen_single().
 def struct_fact(density,name,imgdpi):
     fig, ax = plt.subplots()
     #f = plt.quiver(gx,gy)
     f = plt.imshow((np.abs(np.fft.fftshift(np.fft.fft2(density)))),cmap=plt.get_cmap('prism'))
     cbar = fig.colorbar(f)
     cbar.set_clim(1e6,1e11)
     plt.jet()
     plt.savefig(name + "_struct_log10.png",dpi=imgdpi)
     plt.close()
voronoi()
def vis.voronoi (dataName, dataType, value)
Definition at line 63 of file vis.py.
 def voronoi(dataName,dataType,value):
     v_arr=genfromtxt(dataName + str(value) + dataType,delimiter=',' )
     data = [[row[0],row[1]] for row in v_arr]
     vor = Voronoi(data)
     voronoi_plot_2d(vor)
     plt.xlim(300,700);plt.ylim(300,700);
     plt.savefig('voronoi_' + str(value) + '.png',dpi=200)
     print 'Saved Voronoi @ t=' + str(value)
vort_traj()
def vis.vort_traj (name, imgdpi)
Definition at line 244 of file vis.py.
 def vort_traj(name,imgdpi):
     evMaxVal_l = evMaxVal
     H=genfromtxt('vort_arr_0',delimiter=',' )
     count=0
     for i1 in range(incr,evMaxVal_l,incr):
         try:
             v_arr=genfromtxt('vort_lsq_' + str(i1) + '.csv',delimiter=',' )
             H=np.column_stack((H,v_arr))
         except:
             evMaxVal_l = i1
             break
     X=np.zeros((evMaxVal_l/incr),dtype=np.float64)
     Y=np.zeros((evMaxVal_l/incr),dtype=np.float64)
     H=np.reshape(H,([num_vort,2,evMaxVal_l/incr]),order='F')
     for i1 in range(0, num_vort):
         for i2 in range(0,evMaxVal_l/incr):
             X[i2]=(H[i1,0,i2]*dx) - xMax
             Y[i2]=(H[i1,1,i2]*dx) - yMax
         h = plt.plot(X,Y,color=(r.random(),r.random(),r.random(),0.85),linewidth=0.1)
     plt.axis('equal')
     plt.title('Vort(x,y) from t=0 to t='+str(evMaxVal_l*dt)+" s")
     plt.axis((-xMax/2.0, xMax/2.0, -yMax/2.0, yMax/2.0))
     plt.ticklabel_format(style='scientific')
     plt.ticklabel_format(style='scientific',axis='x', scilimits=(0,0))
     plt.ticklabel_format(style='scientific',axis='y', scilimits=(0,0))
     plt.savefig(name +".pdf")
     plt.close()
     print "Trajectories plotted."
Variable Documentation
c
vis.c = ConfigParser.ConfigParser()
Definition at line 35 of file vis.py.
CPUs
vis.CPUs = os.environ['SLURM_JOB_CPUS_PER_NODE']
Definition at line 12 of file vis.py.
data
vis.data = numpy.ndarray(shape=(xDim,yDim))
Definition at line 52 of file vis.py.
dt
tuple vis.dt = (c.getfloat('Params','dt'))
Definition at line 47 of file vis.py.
dx
tuple vis.dx = (c.getfloat('Params','dx'))
Definition at line 46 of file vis.py.
ev_proc
list vis.ev_proc = []
Definition at line 311 of file vis.py.
evImgList
list vis.evImgList = []
Definition at line 305 of file vis.py.
evMaxVal
vis.evMaxVal = int(c.getfloat('Params','esteps'))
Definition at line 43 of file vis.py.
gnd_proc
list vis.gnd_proc = []
Definition at line 310 of file vis.py.
gndImgList
list vis.gndImgList = []
Definition at line 304 of file vis.py.
gndMaxVal
vis.gndMaxVal = int(c.getfloat('Params','gsteps'))
Definition at line 42 of file vis.py.
i
list vis.i = gndImgList.pop()
Definition at line 313 of file vis.py.
incr
vis.incr = int(c.getfloat('Params','print_out'))
Definition at line 44 of file vis.py.
num_vort
int vis.num_vort = 0
Definition at line 50 of file vis.py.
p
list vis.p = proc.pop()
Definition at line 325 of file vis.py.
prec
vis.prec
Definition at line 34 of file vis.py.
proc
list vis.proc = gnd_proc + ev_proc
Definition at line 319 of file vis.py.
sep
tuple vis.sep = (c.getfloat('Params','dx'))
Definition at line 45 of file vis.py.
xDim
vis.xDim = int(c.getfloat('Params','xDim'))
Definition at line 40 of file vis.py.
xMax
tuple vis.xMax = (c.getfloat('Params','xMax'))
Definition at line 48 of file vis.py.
yDim
vis.yDim = int(c.getfloat('Params','yDim'))
Definition at line 41 of file vis.py.
yMax
tuple vis.yMax = (c.getfloat('Params','yMax'))
Definition at line 49 of file vis.py.